### ISSUE TITLE
Backup failed?

### ISSUE THREAD

**Issue by Qpernicus** [jcwillox/hass-auto-backup#20]
I use stock autobackup incl automations. For the last 2 backups (4 or 5 days) I get a notification of a failed backup 

Logger: custom_components.auto_backup
Source: custom_components/auto_backup/__init__.py:355 
Integration: Auto Backup (documentation) 
First occurred: 2:50:00 (1 occurrences) 
Last logged: 2:50:00

Error during backup. Timeout on /snapshots/new/full request

But when i go to snapshots there is a snapshot there.  Does it try several times? What can i do to localize the cause of this ?

**Comment by jcwillox** [comment]
Basically, the snapshots are taking to long to create. The default timeout is set at 20 minutes, after that, it assumes the backup failed, but more often than not the supervisor goes on to create the backup successfully.
You can increase the default timeout using the [`backup_timeout`](https://github.com/jcwillox/hass-auto-backup#configuration) configuration option, that usually fixes the issue.

The timeout is only there because things start to get unreliable when the backups take to long, it's not a great solution, I am looking at some alternatives but most require some changes on Home Assistants end.

**Comment by Qpernicus** [comment]
I will change the timeout.. The backup is quite large, so i assume thats it.
