### ISSUE TITLE
Backup times out after 1200 seconds

### ISSUE THREAD

**Issue by henriklund** [jcwillox/hass-auto-backup#34]
Lately my automated backups have started to fail. Looking in the Supervisor shows to have completed correctly (similar size as previous backups etc.), however, the supervisor log does not show any download events. Also the backup destination folder is now empty whereas /backup does contain the proper backup.

Enabling debug shows entries like following when triggering automated backups:

 2021-05-16 10:22:20 DEBUG (MainThread) [custom_components.auto_backup] New snapshot; command: /snapshots/new/partial, keep_days: 2.0, data: {'name': 'Hassio_backup_2021_05_16_10_22', 'password': '<hidden>', 'addons': [......], 'folders': [......]}, timeout: 1200.0 seconds
....
2021-05-16 10:42:20 ERROR (MainThread) [custom_components.auto_backup] Error during backup. Timeout on /snapshots/new/partial request

I have not been able to identify the source for the 1200 seconds / 20 mins. However, I have tried following (based on what I found when googling / looking at the code):

Change configurations.yaml to:
auto_backup:
  backup_timeout: 2400

Adjusted consts.py file to:
DEFAULT_BACKUP_TIMEOUT_SECONDS = 2400
DEFAULT_BACKUP_TIMEOUT = 40

Neither of above make any difference. I still face the 20min 'hard stop' for backups.  Any suggestions?

**Comment by jcwillox** [comment]
The `configuration.yaml` method is deprecated and Auto Backup is now configured via the UI, you can change the backup timeout by clicking on options for Auto Backup on the Integrations page. 

Basically, this means your backups must be taking more than 20 minutes to create and Auto Backup assumes they failed, this is because if your backups are taking that long then you are more likely to run into issues when using Auto Backup, you are free to increase the timeout but its kinda in the unsupported realm.

It's worth noting that even if Auto Backup times out the Supervisor will likely still create the backup, but Auto Backup won't track or download that backup as it doesn't know when it completed.

**Comment by henriklund** [comment]
Thanks for the feedback. I changed the timeout in the config and it now lets me run the backup to completion. Maybe I should consider splitting the backup...

I did also note that the backups were completed by Supervisor. I use the 'success' event of Auto Backup to initiate an FTP upload of the backup files, and also get notifications sent whenever the backup fails.
