### ISSUE TITLE
Error on Hass.io API: No slug was returned.

### ISSUE THREAD

**Issue by deluxestyle** [jcwillox/hass-auto-backup#4]
Tried to run the component on my hass.io docker installation with home assistant 0.102.3
But if I try to call auto_backup.snapshot_full then I got following error:
Error on Hass.io API: No slug was returned.

**Comment by jcwillox** [comment]
Hi, this error is likely because `Hass.io` is failing to create the backup. 
What service data are you using with `auto_backup.snapshot_full`?
Also does `auto_backup.snapshot_partial` still work?

Just did a bit of testing, and I managed to get that error if I try to create another backup before one finishes, could that be what's happening?

**Comment by deluxestyle** [comment]
Ah you’re Right. It seems it was already running. Sorry for the confusion
