### ISSUE TITLE
Error "Config flow could not be loaded" at intall

### ISSUE THREAD

**Issue by adbig** [jcwillox/hass-auto-backup#40]
Hi,

When I try to install your integration I have the error  "Config flow could not be loaded" .
Home Assistant OS 6.2  ; Version : core-2021.8.8

I've also setup correctly my internal and external access URL because I've seen that it could be the reason of this error.

Thank you .

Regards,

Adrien

**Comment by picotrain77** [comment]
Thanks although I didn't see the option to install older version (probably me to be honest) I love the look of this and as the 2021.9 is only a matter or a few days away I will wait for that and then set this up. Thanks again 👍🏻

**Comment by jcwillox** [comment]
Ok wow, you're right, I just tried it and you actually cant install it even if you try and select an older version that is compatible. That's very unfortunate and not what I expected at all, I might file a bug report for this. 

So for anyone who wants to install Auto Backup on versions <2021.9, currently the only way to do it is to manually download [auto_backup.zip](https://github.com/jcwillox/hass-auto-backup/releases/download/0.8.0/auto_backup.zip) from release [0.8.0](https://github.com/jcwillox/hass-auto-backup/releases/tag/0.8.0), and then extract the contents to `custom_components/auto_backup`. 
If you later upgrade to 2021.9 you can just install or reinstall Auto Backup through HACS to upgrade to the newer version.

**Comment by adbig** [comment]
Hi,

Even with the latest HomeAssitant version, I'm still not able to install you add-on. I've got the same errorthan I described in my first post.

Adrien

**Comment by jcwillox** [comment]
I just tested this and I was definitely able to download and install the integration, so I'm not sure what's happening. I'd recommend you try and fully reinstall Auto Backup:

* Uninstall the integration from HACS, (i.e. try to remove it completely from HA).
* Restart HA
* Install Auto Backup from HACS (make sure its the latest version `0.9.2`)
* Restart HA
* Setup Auto Backup (i.e. Configuration -> Integrations -> Add Integration -> Auto Backup)

Hopefully that'll get it working otherwise it may be an issue external to Auto Backup such as this
https://community.home-assistant.io/t/hacs-installing-problem-via-integration-error-config-flow-could-not-be-loaded/314501

**Comment by adbig** [comment]
Hi,

I already have the latest 0.9.2 revision and restarted many times my HA :)
I can't uninstall it because I never manage to intall it :-D When I go in Configuration -> Integrations -> Add Integration menu your integration never appears in the list. It's the reason why I used the Badge link to install it .

**Comment by adbig** [comment]
It's OK for , me , I've just manage to install it throught HACS.
I close this issue.

Thank you for your time and help.

Adrien.
