### ISSUE TITLE
You must be running Home Assistant Supervised or have the 'backup' integration enabled

### ISSUE THREAD

**Issue by Kobbe1** [jcwillox/hass-auto-backup#54]
Hej,

Getting below error in an HA container install. But only after restart, it works if I delete the integration and reenable it so I suspect it is a timing issue at startup? Or is it not supposed to work in an container install? It does work if I do not restart ...

`You must be running Home Assistant Supervised or have the 'backup' integration enabled`

**Comment by jcwillox** [comment]
Yeah, I actually noticed that after a restart as well, I thought it was just some glitch in development, but I fixed it by adding `backup:` to the `configuration.yaml` manually. I'll try to figure out why it's doing it.

**Comment by jcwillox** [comment]
Ok, I had a closer look and it appears to actually be an issue with `after_dependencies` in the `manifest.json` which should ensure that the `backup` integration loads before Auto Backup. It seems the issue is only with integration included by `default_config` as when manually adding `backup` to your config it works correctly. So I'll probably have to open an issue with Home Assistant for this.

**Comment by Kobbe1** [comment]
Great, that seems to fix it, no more error after reboot.
Thanks!
I will leave it to you to close this or test further ...

**Comment by jcwillox** [comment]
Sweet glad that's working properly now 👍
